import type { OwnerWorkspaceSnapshot } from '@/lib/types/owner';

export const ownerMockData: OwnerWorkspaceSnapshot = {
  navigation: [
    { key: 'overview', label: 'Overview', href: '/dashboard/owner', helper: 'Inbox', badge: '4' },
    { key: 'pipelines', label: 'Pipelines', href: '/dashboard/owner/pipelines', helper: '7 active' },
    { key: 'openclaw', label: 'OpenClaw Chat', href: '/dashboard/owner/groupchat', helper: '2 unread', badge: '2' },
    { key: 'suggestions', label: 'Suggestions', href: '/dashboard/owner/suggestions', helper: '9 review' },
    { key: 'import-bot', label: 'Import Bot', href: '/dashboard/owner/import-bot', helper: '1 pending' },
    { key: 'bots', label: 'Bot Management', href: '/dashboard/owner/bot-management', helper: '12 bots' },
    { key: 'outputs', label: 'Outputs', href: '/dashboard/owner/outputs', helper: '18 review' },
    { key: 'code-refinements', label: 'Code Refinements', href: '/dashboard/owner/code-refinements', helper: '3 ready' },
    { key: 'settings', label: 'Settings', href: '/dashboard/owner/settings' },
  ],
  pipelines: [
    {
      id: 'pipeline-code',
      name: 'Code',
      slug: 'code',
      description: 'Owner dashboard implementation work, product UI tasks, and execution-ready refinements.',
      status: 'active',
      accent: '#4f46e5',
      lastActivityAt: '2026-03-18T03:58:00.000Z',
      botIds: ['bot-orchestrator', 'bot-spec-weaver', 'bot-review'],
      outputIds: ['output-refactor-shell', 'output-openclaw-room'],
      suggestionIds: ['suggestion-owner-shell', 'suggestion-thread-summary'],
      threadIds: ['thread-owner-hq', 'thread-code-shell'],
      routingRules: {
        intake: 'UI requests, owner prompts, output escalations',
        review: 'Code refinements before shipping',
        dispatch: 'Cursor handoff or direct implementation',
      },
    },
    {
      id: 'pipeline-marketing',
      name: 'Marketing',
      slug: 'marketing',
      description: 'Launch notes, founder messaging, and product positioning drafts.',
      status: 'watching',
      accent: '#f97316',
      lastActivityAt: '2026-03-18T03:29:00.000Z',
      botIds: ['bot-launch-copy'],
      outputIds: ['output-launch-copy'],
      suggestionIds: ['suggestion-founder-story'],
      threadIds: ['thread-marketing-copy'],
      routingRules: {
        intake: 'Approved founder ideas and copy briefs',
        review: 'Owner review in Suggestions or Outputs',
        dispatch: 'Social or site copy',
      },
    },
    {
      id: 'pipeline-social',
      name: 'Social',
      slug: 'social',
      description: 'Short-form variations and distribution-ready drafts.',
      status: 'active',
      accent: '#14b8a6',
      lastActivityAt: '2026-03-18T03:10:00.000Z',
      botIds: ['bot-social-cut'],
      outputIds: ['output-social-thread'],
      suggestionIds: [],
      threadIds: [],
      routingRules: {
        intake: 'Approved marketing copy',
        review: 'Output review queue',
        dispatch: 'Publishing tools',
      },
    },
    {
      id: 'pipeline-product',
      name: 'Product',
      slug: 'product',
      description: 'Feature direction, workflow design, and backlog shaping.',
      status: 'active',
      accent: '#a16207',
      lastActivityAt: '2026-03-18T02:47:00.000Z',
      botIds: ['bot-product-signal'],
      outputIds: ['output-product-spec'],
      suggestionIds: ['suggestion-import-scorecard'],
      threadIds: [],
      routingRules: {
        intake: 'Feature requests and owner notes',
        review: 'Suggestions page',
        dispatch: 'Backlog or code pipeline',
      },
    },
    {
      id: 'pipeline-seo',
      name: 'SEO',
      slug: 'seo',
      description: 'Search notes, content opportunities, and technical SEO follow-up.',
      status: 'paused',
      accent: '#2563eb',
      lastActivityAt: '2026-03-18T02:11:00.000Z',
      botIds: ['bot-search'],
      outputIds: ['output-seo-brief'],
      suggestionIds: [],
      threadIds: [],
      routingRules: {
        intake: 'Docs and content changes',
        review: 'Suggestions first',
        dispatch: 'Content updates',
      },
    },
    {
      id: 'pipeline-experiments',
      name: 'Experiments',
      slug: 'experiments',
      description: 'Trials, prompts, and temporary routing ideas before promotion.',
      status: 'watching',
      accent: '#7c3aed',
      lastActivityAt: '2026-03-18T03:01:00.000Z',
      botIds: ['bot-prompt-lab'],
      outputIds: [],
      suggestionIds: ['suggestion-thread-summary'],
      threadIds: [],
      routingRules: {
        intake: 'Owner what-if prompts',
        review: 'Suggestions',
        dispatch: 'Promote to stable pipeline',
      },
    },
    {
      id: 'pipeline-custom',
      name: 'Custom',
      slug: 'custom',
      description: 'Imported bots, staging work, and custom owner investigations.',
      status: 'active',
      accent: '#64748b',
      lastActivityAt: '2026-03-18T03:34:00.000Z',
      botIds: ['bot-import-stage'],
      outputIds: ['output-import-review'],
      suggestionIds: [],
      threadIds: ['thread-import-review'],
      routingRules: {
        intake: 'Imported configs and custom prompts',
        review: 'Import review and bot management',
        dispatch: 'Assign into primary pipelines',
      },
    },
  ],
  bots: [
    {
      id: 'bot-orchestrator',
      name: 'Quartz Prime',
      description: 'Routes work, summarizes threads, and keeps the owner inbox clean.',
      systemPrompt: 'Keep owner workflows concise, useful, and easy to act on.',
      status: 'active',
      health: 'healthy',
      model: 'gpt-5.4',
      pipelineId: 'pipeline-code',
      tools: ['chat', 'routing', 'suggestions'],
      permissions: ['assign threads', 'move suggestions', 'route outputs'],
      lastActiveAt: '2026-03-18T03:58:00.000Z',
      taskCount: 4,
      recentOutputIds: ['output-refactor-shell'],
      recentThreadIds: ['thread-owner-hq'],
      logs: [
        { id: 'log-1', level: 'info', message: 'Summarized active review queue.', createdAt: '2026-03-18T03:58:00.000Z' },
      ],
    },
    {
      id: 'bot-spec-weaver',
      name: 'Spec Weaver',
      description: 'Formats code work into plain-English execution specs.',
      systemPrompt: 'Write implementation specs that another AI can execute directly.',
      status: 'active',
      health: 'healthy',
      model: 'claude-3.7-sonnet',
      pipelineId: 'pipeline-code',
      tools: ['refinements', 'outputs'],
      permissions: ['create refinements', 'update refinement status'],
      lastActiveAt: '2026-03-18T03:41:00.000Z',
      taskCount: 2,
      recentOutputIds: ['output-openclaw-room'],
      recentThreadIds: ['thread-code-shell'],
      logs: [
        { id: 'log-2', level: 'info', message: 'Prepared the OpenClaw workspace refinement.', createdAt: '2026-03-18T03:41:00.000Z' },
      ],
    },
    {
      id: 'bot-review',
      name: 'Review Claw',
      description: 'Checks implementation details and route consistency.',
      systemPrompt: 'Review only for practical quality and route correctness.',
      status: 'idle',
      health: 'watching',
      model: 'gpt-4.1',
      pipelineId: 'pipeline-code',
      tools: ['refinements', 'chat'],
      permissions: ['comment on refinements'],
      lastActiveAt: '2026-03-18T03:06:00.000Z',
      taskCount: 1,
      recentOutputIds: [],
      recentThreadIds: ['thread-code-shell'],
      logs: [
        { id: 'log-3', level: 'warning', message: 'Waiting on owner decision for shell rewrite.', createdAt: '2026-03-18T03:06:00.000Z' },
      ],
    },
    {
      id: 'bot-launch-copy',
      name: 'Launch Copy',
      description: 'Writes quiet, founder-led marketing copy.',
      systemPrompt: 'Keep messaging grounded and specific.',
      status: 'active',
      health: 'healthy',
      model: 'gpt-4o',
      pipelineId: 'pipeline-marketing',
      tools: ['outputs', 'suggestions'],
      permissions: ['draft copy'],
      lastActiveAt: '2026-03-18T03:29:00.000Z',
      taskCount: 2,
      recentOutputIds: ['output-launch-copy'],
      recentThreadIds: ['thread-marketing-copy'],
      logs: [
        { id: 'log-4', level: 'info', message: 'Rewrote the founder note intro.', createdAt: '2026-03-18T03:29:00.000Z' },
      ],
    },
    {
      id: 'bot-social-cut',
      name: 'Social Cut',
      description: 'Adapts approved copy into short-form outputs.',
      systemPrompt: 'Stay concise and natural.',
      status: 'idle',
      health: 'healthy',
      model: 'gpt-4.1-mini',
      pipelineId: 'pipeline-social',
      tools: ['outputs'],
      permissions: ['draft social copy'],
      lastActiveAt: '2026-03-18T03:10:00.000Z',
      taskCount: 1,
      recentOutputIds: ['output-social-thread'],
      recentThreadIds: [],
      logs: [
        { id: 'log-5', level: 'info', message: 'Queued a short X thread draft.', createdAt: '2026-03-18T03:10:00.000Z' },
      ],
    },
    {
      id: 'bot-product-signal',
      name: 'Product Signal',
      description: 'Turns owner notes into scoped product suggestions.',
      systemPrompt: 'Focus on useful product changes, not vague vision language.',
      status: 'active',
      health: 'healthy',
      model: 'gpt-4.1',
      pipelineId: 'pipeline-product',
      tools: ['suggestions', 'outputs'],
      permissions: ['create product ideas'],
      lastActiveAt: '2026-03-18T02:47:00.000Z',
      taskCount: 1,
      recentOutputIds: ['output-product-spec'],
      recentThreadIds: [],
      logs: [
        { id: 'log-6', level: 'info', message: 'Produced import scorecard recommendation.', createdAt: '2026-03-18T02:47:00.000Z' },
      ],
    },
    {
      id: 'bot-search',
      name: 'Search Claw',
      description: 'Tracks search issues and SEO follow-up.',
      systemPrompt: 'Focus on concrete content and technical SEO work.',
      status: 'paused',
      health: 'error',
      model: 'sonnet-reasoning',
      pipelineId: 'pipeline-seo',
      tools: ['outputs', 'suggestions'],
      permissions: ['draft briefs'],
      lastActiveAt: '2026-03-18T02:11:00.000Z',
      taskCount: 0,
      recentOutputIds: ['output-seo-brief'],
      recentThreadIds: [],
      logs: [
        { id: 'log-7', level: 'error', message: 'Search Console credentials are missing.', createdAt: '2026-03-18T02:11:00.000Z' },
      ],
    },
    {
      id: 'bot-prompt-lab',
      name: 'Prompt Lab',
      description: 'Tests new flow ideas before promotion.',
      systemPrompt: 'Experiment without polluting the main review inbox.',
      status: 'idle',
      health: 'watching',
      model: 'gpt-4.1-mini',
      pipelineId: 'pipeline-experiments',
      tools: ['suggestions'],
      permissions: ['create experiment suggestions'],
      lastActiveAt: '2026-03-18T03:01:00.000Z',
      taskCount: 1,
      recentOutputIds: [],
      recentThreadIds: [],
      logs: [
        { id: 'log-8', level: 'info', message: 'Queued thread summary workflow test.', createdAt: '2026-03-18T03:01:00.000Z' },
      ],
    },
    {
      id: 'bot-import-stage',
      name: 'Import Stage',
      description: 'Validates incoming bot configs before activation.',
      systemPrompt: 'Treat imported configs carefully and assign roles before activation.',
      status: 'active',
      health: 'healthy',
      model: 'gpt-4.1',
      pipelineId: 'pipeline-custom',
      tools: ['imports', 'bots'],
      permissions: ['validate imports', 'stage bots'],
      lastActiveAt: '2026-03-18T03:34:00.000Z',
      taskCount: 1,
      recentOutputIds: ['output-import-review'],
      recentThreadIds: ['thread-import-review'],
      logs: [
        { id: 'log-9', level: 'info', message: 'Detected two bots from pasted config.', createdAt: '2026-03-18T03:34:00.000Z' },
      ],
    },
  ],
  threads: [
    {
      id: 'thread-owner-hq',
      title: 'Owner HQ',
      room: 'owner',
      pipelineId: 'pipeline-code',
      participantBotIds: ['bot-orchestrator', 'bot-spec-weaver', 'bot-launch-copy'],
      pinned: true,
      archived: false,
      unreadCount: 2,
      updatedAt: '2026-03-18T03:58:00.000Z',
      summary: 'Current owner queue, approvals, and routing decisions.',
    },
    {
      id: 'thread-code-shell',
      title: 'Owner dashboard rebuild',
      room: 'code',
      pipelineId: 'pipeline-code',
      participantBotIds: ['bot-spec-weaver', 'bot-review'],
      pinned: true,
      archived: false,
      unreadCount: 0,
      updatedAt: '2026-03-18T03:41:00.000Z',
      summary: 'Shell rewrite, routes, search, and interaction model.',
    },
    {
      id: 'thread-marketing-copy',
      title: 'Founder note revision',
      room: 'marketing',
      pipelineId: 'pipeline-marketing',
      participantBotIds: ['bot-launch-copy'],
      pinned: false,
      archived: false,
      unreadCount: 0,
      updatedAt: '2026-03-18T03:29:00.000Z',
      summary: 'Quiet rewrite of the launch note.',
    },
    {
      id: 'thread-import-review',
      title: 'Import review staging',
      room: 'research',
      pipelineId: 'pipeline-custom',
      participantBotIds: ['bot-import-stage', 'bot-product-signal'],
      pinned: false,
      archived: false,
      unreadCount: 1,
      updatedAt: '2026-03-18T03:34:00.000Z',
      summary: 'Imported bot config review and assignment decisions.',
    },
  ],
  messages: [
    {
      id: 'message-1',
      threadId: 'thread-owner-hq',
      authorType: 'bot',
      authorId: 'bot-orchestrator',
      authorLabel: 'Quartz Prime',
      content: 'Four items still need review: two suggestions, one refinement, and one imported config.',
      createdAt: '2026-03-18T03:50:00.000Z',
      status: 'done',
    },
    {
      id: 'message-2',
      threadId: 'thread-owner-hq',
      authorType: 'owner',
      authorId: 'owner',
      authorLabel: 'Owner',
      content: 'Keep the shell minimal. No oversized overview cards and no fake dashboard language.',
      createdAt: '2026-03-18T03:52:00.000Z',
      status: 'done',
    },
    {
      id: 'message-3',
      threadId: 'thread-owner-hq',
      authorType: 'bot',
      authorId: 'bot-spec-weaver',
      authorLabel: 'Spec Weaver',
      content: 'Understood. I will keep the main surface dense and rely on lists, tables, and a clean chat workspace.',
      createdAt: '2026-03-18T03:54:00.000Z',
      status: 'done',
    },
    {
      id: 'message-4',
      threadId: 'thread-code-shell',
      authorType: 'bot',
      authorId: 'bot-review',
      authorLabel: 'Review Claw',
      content: 'The current layout is too presentation-heavy. Move to a tighter app shell with fixed navigation and a workspace-first center column.',
      createdAt: '2026-03-18T03:41:00.000Z',
      status: 'done',
    },
    {
      id: 'message-5',
      threadId: 'thread-marketing-copy',
      authorType: 'bot',
      authorId: 'bot-launch-copy',
      authorLabel: 'Launch Copy',
      content: 'I shortened the intro and removed the generic “building the future” phrasing.',
      createdAt: '2026-03-18T03:29:00.000Z',
      status: 'done',
    },
    {
      id: 'message-6',
      threadId: 'thread-import-review',
      authorType: 'bot',
      authorId: 'bot-import-stage',
      authorLabel: 'Import Stage',
      content: 'The pasted config validates. Two bots were detected and both should remain inactive until pipeline assignment is confirmed.',
      createdAt: '2026-03-18T03:34:00.000Z',
      status: 'done',
    },
  ],
  suggestions: [
    {
      id: 'suggestion-owner-shell',
      title: 'Default UI requests into Code before they spread elsewhere',
      category: 'Workflow improvement',
      priority: 'high',
      status: 'review',
      pipelineId: 'pipeline-code',
      botId: 'bot-orchestrator',
      createdAt: '2026-03-18T03:48:00.000Z',
      summary: 'Owner dashboard requests should land in Code first so the implementation path stays coherent.',
      detail: 'Use Code as the default entry pipeline for anything involving shell behavior, page structure, layout, interactions, or state architecture.',
      cursorPayload: 'Route owner dashboard UI work into Code first. Only move it elsewhere after a concrete implementation path exists.',
    },
    {
      id: 'suggestion-thread-summary',
      title: 'Add a one-click thread summary action for long OpenClaw conversations',
      category: 'Automation opportunity',
      priority: 'medium',
      status: 'review',
      pipelineId: 'pipeline-experiments',
      botId: 'bot-prompt-lab',
      createdAt: '2026-03-18T03:01:00.000Z',
      summary: 'Long owner threads need a summary action that surfaces next steps without manual cleanup.',
      detail: 'Support a summary action that extracts decisions, blockers, and likely routing destinations from the active thread.',
      cursorPayload: 'Implement a summarize action in OpenClaw chat that creates a concise owner-ready handoff.',
    },
    {
      id: 'suggestion-founder-story',
      title: 'Tie launch messaging to real product workflows',
      category: 'Marketing idea',
      priority: 'medium',
      status: 'approved',
      pipelineId: 'pipeline-marketing',
      botId: 'bot-launch-copy',
      createdAt: '2026-03-18T03:12:00.000Z',
      summary: 'Explain Quartz through actual owner actions instead of general claims.',
      detail: 'Anchor any founder message in real product workflows like reviewing outputs, assigning bots, and routing refinements.',
      cursorPayload: 'Rewrite launch copy around actual owner workflows instead of abstract AI promises.',
    },
    {
      id: 'suggestion-import-scorecard',
      title: 'Score imported bots by permission risk and routing fit',
      category: 'Product idea',
      priority: 'high',
      status: 'review',
      pipelineId: 'pipeline-product',
      botId: 'bot-product-signal',
      createdAt: '2026-03-18T02:47:00.000Z',
      summary: 'Imported configs feel safer when the app shows role fit, tool risk, and a suggested pipeline before activation.',
      detail: 'Add a compact scorecard during import so the owner can review each bot before saving.',
      cursorPayload: 'Create an import scorecard with risk, suggested pipeline, and active toggle defaults.',
    },
  ],
  outputs: [
    {
      id: 'output-refactor-shell',
      title: 'Owner shell rewrite plan',
      type: 'Code refinement',
      status: 'review',
      pipelineId: 'pipeline-code',
      botId: 'bot-orchestrator',
      createdAt: '2026-03-18T03:44:00.000Z',
      preview: 'Restructure the owner area around a fixed sidebar and dense central workspace.',
      content: 'Replace the oversized overview layout with a compact app shell. Use fixed navigation, contextual lists, and real local actions.',
    },
    {
      id: 'output-openclaw-room',
      title: 'OpenClaw chat workspace spec',
      type: 'Code refinement',
      status: 'review',
      pipelineId: 'pipeline-code',
      botId: 'bot-spec-weaver',
      createdAt: '2026-03-18T03:41:00.000Z',
      preview: 'A three-column chat workspace with real thread switching and command parsing.',
      content: 'Build a left room list, central message area, and right detail panel with a sticky composer and command support.',
    },
    {
      id: 'output-launch-copy',
      title: 'Founder launch note rewrite',
      type: 'Marketing copy',
      status: 'review',
      pipelineId: 'pipeline-marketing',
      botId: 'bot-launch-copy',
      createdAt: '2026-03-18T03:29:00.000Z',
      preview: 'A quieter note with less category language and more product specificity.',
      content: 'Quartz is becoming a better private workspace for routing work and reviewing output, not a louder AI product.',
    },
    {
      id: 'output-social-thread',
      title: 'Short X thread draft',
      type: 'Social draft',
      status: 'approved',
      pipelineId: 'pipeline-social',
      botId: 'bot-social-cut',
      createdAt: '2026-03-18T03:10:00.000Z',
      preview: 'A concise three-post thread for founder distribution.',
      content: 'Drafted a short social thread connected to the launch note.',
    },
    {
      id: 'output-product-spec',
      title: 'Import scorecard product note',
      type: 'Product spec',
      status: 'review',
      pipelineId: 'pipeline-product',
      botId: 'bot-product-signal',
      createdAt: '2026-03-18T02:47:00.000Z',
      preview: 'A compact scoring model for imported bots.',
      content: 'Show role fit, tool risk, and suggested pipeline before import confirmation.',
    },
    {
      id: 'output-seo-brief',
      title: 'Search Console reconnect note',
      type: 'SEO brief',
      status: 'review',
      pipelineId: 'pipeline-seo',
      botId: 'bot-search',
      createdAt: '2026-03-18T02:11:00.000Z',
      preview: 'SEO reporting is paused until credentials are fixed.',
      content: 'Reconnect Search Console to restore ranking deltas and indexed coverage views.',
    },
    {
      id: 'output-import-review',
      title: 'Import review summary',
      type: 'Bot system notice',
      status: 'review',
      pipelineId: 'pipeline-custom',
      botId: 'bot-import-stage',
      createdAt: '2026-03-18T03:34:00.000Z',
      preview: 'Two bots detected and staged for approval.',
      content: 'The uploaded config produced two bots. Both remain inactive until pipeline assignment is confirmed.',
    },
  ],
  refinements: [
    {
      id: 'refinement-shell',
      title: 'Owner dashboard shell rewrite',
      pipelineId: 'pipeline-code',
      botId: 'bot-spec-weaver',
      status: 'review',
      createdAt: '2026-03-18T03:43:00.000Z',
      filesToChange: ['app/dashboard/owner/layout.tsx', 'components/owner/OwnerSidebar.tsx', 'components/owner/OwnerShell.tsx'],
      suggestion: 'Rebuild the owner dashboard shell around a fixed left sidebar, compact global search, and a clean scrollable workspace. Remove oversized overview cards and favor dense lists, tables, and real workspace panels.',
      whyThisHelps: 'It makes the owner area feel like real software, improves navigation speed, and creates a stable foundation for functional multi-page workflows.',
      alternativeApproaches: ['Keep a minimal two-column shell with a collapsible utility panel.', 'Use a single-column layout on narrow widths while preserving the desktop sidebar logic.', 'Keep search embedded in the sidebar rather than adding a top bar.'],
    },
    {
      id: 'refinement-openclaw',
      title: 'OpenClaw chat workspace',
      pipelineId: 'pipeline-code',
      botId: 'bot-spec-weaver',
      status: 'review',
      createdAt: '2026-03-18T03:41:00.000Z',
      filesToChange: ['app/dashboard/owner/groupchat/page.tsx', 'components/owner/ChatThreadList.tsx', 'components/owner/ChatComposer.tsx'],
      suggestion: 'Implement a practical chat workspace with room switching, search, pin and archive actions, thread state, and a sticky command-aware composer.',
      whyThisHelps: 'It turns the chat page into a usable owner workspace instead of a presentation surface.',
      alternativeApproaches: ['Collapse the right context panel by default.', 'Open thread details in a drawer rather than a persistent side panel.', 'Use keyboard-first navigation for room switching.'],
    },
    {
      id: 'refinement-refinement-list',
      title: 'Refinement queue with explicit execution actions',
      pipelineId: 'pipeline-code',
      botId: 'bot-review',
      status: 'review',
      createdAt: '2026-03-18T03:06:00.000Z',
      filesToChange: ['app/dashboard/owner/code-refinements/page.tsx', 'components/owner/CodeRefinementList.tsx'],
      suggestion: 'Show refinements in a dense list with copy, send-to-Cursor, mark applied, reject, assign to bot, and pipeline link actions available per item.',
      whyThisHelps: 'It makes the refinements page work like a real review queue rather than a static reading surface.',
      alternativeApproaches: ['Use a split list and detail pane.', 'Open each refinement in a drawer from the list.', 'Keep inline expansion for quick scanning.'],
    },
  ],
  imports: [
    {
      id: 'import-1',
      source: 'OpenClaw',
      fileName: 'launch-week.openclaw.json',
      rawConfig: '{"source":"OpenClaw","bots":[{"name":"Hook Draft","model":"gpt-4.1","role":"social hooks","tools":["outputs"]},{"name":"Reply Triage","model":"gpt-4.1-mini","role":"community replies","tools":["chat"]}]}',
      status: 'validated',
      createdAt: '2026-03-18T03:34:00.000Z',
      detectedBots: [
        {
          id: 'import-bot-1',
          name: 'Hook Draft',
          model: 'gpt-4.1',
          role: 'social hooks',
          tools: ['outputs'],
          suggestedPipelineId: 'pipeline-social',
          active: false,
        },
        {
          id: 'import-bot-2',
          name: 'Reply Triage',
          model: 'gpt-4.1-mini',
          role: 'community replies',
          tools: ['chat'],
          suggestedPipelineId: 'pipeline-custom',
          active: false,
        },
      ],
    },
  ],
  approvals: [
    {
      id: 'approval-1',
      title: 'Owner shell rewrite plan',
      kind: 'refinement',
      targetId: 'refinement-shell',
      pipelineId: 'pipeline-code',
      createdAt: '2026-03-18T03:43:00.000Z',
      summary: 'The shell needs a full layout reset before more page work lands on top of it.',
    },
    {
      id: 'approval-2',
      title: 'Launch-week config import',
      kind: 'import',
      targetId: 'import-1',
      pipelineId: 'pipeline-custom',
      createdAt: '2026-03-18T03:34:00.000Z',
      summary: 'Two imported bots are ready for pipeline assignment and activation review.',
    },
  ],
  activity: [
    {
      id: 'activity-1',
      label: 'Quartz Prime updated Owner HQ',
      detail: 'The active review queue was summarized and two pending approvals were surfaced.',
      createdAt: '2026-03-18T03:58:00.000Z',
      pipelineId: 'pipeline-code',
      threadId: 'thread-owner-hq',
    },
    {
      id: 'activity-2',
      label: 'Import Stage validated a pasted config',
      detail: 'Two bots were detected and staged as inactive until assignment is confirmed.',
      createdAt: '2026-03-18T03:34:00.000Z',
      pipelineId: 'pipeline-custom',
      threadId: 'thread-import-review',
    },
    {
      id: 'activity-3',
      label: 'Launch Copy revised the founder note',
      detail: 'The draft is ready to review in Outputs.',
      createdAt: '2026-03-18T03:29:00.000Z',
      pipelineId: 'pipeline-marketing',
      threadId: 'thread-marketing-copy',
    },
  ],
  settings: {
    ownerEmail: 'aiden@quartzeditor.com',
    requireOwnerCheck: true,
    defaultModel: 'gpt-5.4',
    defaultPipelineId: 'pipeline-code',
    routeNewUiWorkToCode: true,
    compactMode: true,
    notifications: {
      approvals: true,
      imports: true,
      threadMentions: true,
    },
    integrations: {
      kiloClawApiKey: '••••••••••••••',
      openClawConfigPath: 'configs/openclaw.json',
      cursorWorkspace: 'Quartz Owner Workspace',
    },
  },
};

export function createOwnerMockData() {
  return JSON.parse(JSON.stringify(ownerMockData)) as OwnerWorkspaceSnapshot;
}
