import type {
  BotRecord,
  CodeRefinementSpec,
  GroupchatContext,
  ImportedBotPackage,
  OwnerActivityItem,
  OwnerAlertItem,
  OwnerApprovalItem,
  OwnerNavItem,
  OwnerOutput,
  OwnerQuickAction,
  OwnerSettingSection,
  OwnerSignal,
  OwnerSuggestion,
  PipelineSummary,
} from './types';

export const ownerNavigation: OwnerNavItem[] = [
  { label: 'Overview', href: '/dashboard/owner', description: 'Signals, alerts, approvals', icon: 'overview', shortcut: '1' },
  { label: 'Pipelines', href: '/dashboard/owner/pipelines', description: 'Organize work lanes', icon: 'pipelines', shortcut: '2' },
  { label: 'OpenClaw Groupchat', href: '/dashboard/owner/groupchat', description: 'Talk to all relevant claws', icon: 'groupchat', shortcut: '3' },
  { label: 'Suggestions', href: '/dashboard/owner/suggestions', description: 'Copy-ready ideas and specs', icon: 'suggestions', shortcut: '4' },
  { label: 'Import Bot', href: '/dashboard/owner/import-bot', description: 'Import configs and roles', icon: 'import', shortcut: '5' },
  { label: 'Bot Management', href: '/dashboard/owner/bot-management', description: 'Status, tools, permissions', icon: 'bots', shortcut: '6' },
  { label: 'Outputs', href: '/dashboard/owner/outputs', description: 'Everything claws generated', icon: 'outputs', shortcut: '7' },
  { label: 'Code Refinements', href: '/dashboard/owner/code-refinements', description: 'Plain-English execution specs', icon: 'refinements', shortcut: '8' },
  { label: 'Settings', href: '/dashboard/owner/settings', description: 'Routing, keys, defaults', icon: 'settings', shortcut: '9' },
];

export const overviewSignals: OwnerSignal[] = [
  { id: 'signal-1', label: 'Claws active', value: '12 / 14', detail: '2 watching blocked work', tone: 'success' },
  { id: 'signal-2', label: 'Pending approvals', value: '6', detail: '2 need a decision this morning', tone: 'warning' },
  { id: 'signal-3', label: 'Important alerts', value: '2', detail: 'Code and SEO need attention', tone: 'critical' },
  { id: 'signal-4', label: 'Fresh suggestions', value: '9', detail: 'ready to copy into another AI', tone: 'neutral' },
];

export const overviewActivity: OwnerActivityItem[] = [
  {
    id: 'activity-1',
    agentName: 'Quartz Prime',
    pipelineLabel: 'Overview',
    action: 'Prepared the morning owner briefing',
    detail: 'Grouped overnight work into approvals, blocked items, and suggestions so the queue is easy to clear.',
    createdAtLabel: '2m ago',
    href: '/dashboard/owner/groupchat',
    tone: 'success',
  },
  {
    id: 'activity-2',
    agentName: 'Code Claw 03',
    pipelineLabel: 'Code',
    action: 'Drafted an owner shell refinement spec',
    detail: 'The spec reshapes navigation, routing, and page hierarchy without drifting into a fake admin dashboard aesthetic.',
    createdAtLabel: '9m ago',
    href: '/dashboard/owner/code-refinements',
    tone: 'neutral',
  },
  {
    id: 'activity-3',
    agentName: 'Search Claw',
    pipelineLabel: 'SEO',
    action: 'Flagged stale Search Console credentials',
    detail: 'Cached insights are still available, but live delta reporting is blocked until credentials are refreshed.',
    createdAtLabel: '27m ago',
    href: '/dashboard/owner/settings',
    tone: 'critical',
  },
];

export const overviewAlerts: OwnerAlertItem[] = [
  {
    id: 'alert-1',
    title: 'Code pipeline is routing dashboard work too broadly',
    detail: 'Owner shell requests are mixing with general product ideas instead of landing in the code refinement lane first.',
    severity: 'critical',
    actionLabel: 'Fix routing rule',
    href: '/dashboard/owner/pipelines/code',
  },
  {
    id: 'alert-2',
    title: 'SEO reporting is partially paused',
    detail: 'Live ranking deltas are unavailable until Search Console credentials are refreshed in owner settings.',
    severity: 'warning',
    actionLabel: 'Refresh credentials',
    href: '/dashboard/owner/settings',
  },
  {
    id: 'alert-3',
    title: 'Launch-week OpenClaw bundle is still staged',
    detail: 'Three imported bots are ready for role review and pipeline assignment but none are active yet.',
    severity: 'success',
    actionLabel: 'Inspect import',
    href: '/dashboard/owner/import-bot',
  },
];

export const pendingApprovals: OwnerApprovalItem[] = [
  {
    id: 'approval-1',
    title: 'Owner shell spacing refinement',
    pipelineLabel: 'Code',
    requestedBy: 'Code Claw 03',
    detail: 'Approve before the next implementation pass so layout and card spacing stay consistent across every page.',
    dueLabel: 'Today before 11:30',
    href: '/dashboard/owner/code-refinements',
  },
  {
    id: 'approval-2',
    title: 'Founder launch note rewrite',
    pipelineLabel: 'Marketing',
    requestedBy: 'Launch Copy',
    detail: 'A quieter, more personal note is ready and can be routed into social once approved.',
    dueLabel: 'Today before lunch',
    href: '/dashboard/owner/outputs',
  },
  {
    id: 'approval-3',
    title: 'Custom research pipeline activation',
    pipelineLabel: 'Custom Research',
    requestedBy: 'Quartz Prime',
    detail: 'Imported bots need a stable staging lane before they can promote work into the primary pipelines.',
    dueLabel: 'No hard deadline',
    href: '/dashboard/owner/pipelines/custom-research',
  },
];

export const quickActions: OwnerQuickAction[] = [
  { id: 'quick-1', label: 'Open Groupchat', description: 'Talk to the active claws and clear blockers together.', href: '/dashboard/owner/groupchat' },
  { id: 'quick-2', label: 'Review code refinements', description: 'See plain-English implementation specs ready to hand off.', href: '/dashboard/owner/code-refinements' },
  { id: 'quick-3', label: 'Inspect imported bots', description: 'Assign staged bots to the right pipelines and roles.', href: '/dashboard/owner/import-bot' },
  { id: 'quick-4', label: 'Scan outputs', description: 'Review, copy, route, or send generated work onward.', href: '/dashboard/owner/outputs' },
];

export const ownerPipelines: PipelineSummary[] = [
  {
    slug: 'code',
    name: 'Code',
    description: 'Execution specs, interface refinements, implementation prompts, and quality passes.',
    accent: '#7C83FF',
    status: 'watching',
    focus: 'Keep owner dashboard work structured, human-readable, and easy to hand off.',
    queueCount: 4,
    botCount: 3,
    recentOutputCount: 11,
    routing: {
      intake: 'Groupchat commands, owner notes, flagged outputs',
      review: 'Code refinements first, outputs second',
      dispatch: 'Cursor-ready specs or implementation work',
    },
    assignedBots: ['Code Claw 03', 'Spec Weaver', 'Review Claw'],
    recentOutputs: [
      { id: 'code-1', title: 'Owner shell refinement brief', kind: 'Code refinement', createdAtLabel: '8m ago', status: 'Needs review' },
      { id: 'code-2', title: 'Pipeline detail cleanup', kind: 'Execution spec', createdAtLabel: '22m ago', status: 'Ready' },
    ],
  },
  {
    slug: 'marketing',
    name: 'Marketing',
    description: 'Launch notes, positioning drafts, product framing, and calm editorial copy.',
    accent: '#F29D85',
    status: 'healthy',
    focus: 'Keep Quartz language founder-led and grounded in actual product behavior.',
    queueCount: 3,
    botCount: 2,
    recentOutputCount: 9,
    routing: {
      intake: 'Overview actions and suggestion handoffs',
      review: 'Outputs page',
      dispatch: 'Social, site copy, and founder notes',
    },
    assignedBots: ['Launch Copy', 'Narrative Claw'],
    recentOutputs: [
      { id: 'marketing-1', title: 'Founder launch note rewrite', kind: 'Copy draft', createdAtLabel: '14m ago', status: 'Ready' },
      { id: 'marketing-2', title: 'Homepage subhead alternatives', kind: 'Messaging', createdAtLabel: '37m ago', status: 'Ready' },
    ],
  },
  {
    slug: 'social',
    name: 'Social',
    description: 'Short-form content, founder updates, and platform-specific follow-through from approved drafts.',
    accent: '#7DC8C0',
    status: 'healthy',
    focus: 'Turn approved work into posts without sounding engineered or loud.',
    queueCount: 2,
    botCount: 2,
    recentOutputCount: 7,
    routing: {
      intake: 'Approved marketing drafts',
      review: 'Outputs and Groupchat',
      dispatch: 'X, LinkedIn, Instagram, and waitlist channels',
    },
    assignedBots: ['Social Cut', 'Shortform Notes'],
    recentOutputs: [
      { id: 'social-1', title: 'Founder thread starter', kind: 'Social draft', createdAtLabel: '16m ago', status: 'Ready' },
      { id: 'social-2', title: 'Instagram caption variants', kind: 'Social draft', createdAtLabel: '54m ago', status: 'Needs review' },
    ],
  },
  {
    slug: 'product',
    name: 'Product',
    description: 'Feature concepts, backlog cleanup, roadmap notes, and founder feedback synthesis.',
    accent: '#D7B47E',
    status: 'healthy',
    focus: 'Keep roadmap decisions grounded in taste and actual product utility.',
    queueCount: 5,
    botCount: 2,
    recentOutputCount: 8,
    routing: {
      intake: 'Suggestions and owner prompts',
      review: 'Overview and Suggestions',
      dispatch: 'Roadmap notes and build-ready specs',
    },
    assignedBots: ['Product Signal', 'Roadmap Claw'],
    recentOutputs: [
      { id: 'product-1', title: 'Dashboard backlog cleanup', kind: 'Product note', createdAtLabel: '12m ago', status: 'Ready' },
      { id: 'product-2', title: 'Import flow follow-up ideas', kind: 'Suggestions', createdAtLabel: '1h ago', status: 'Queued' },
    ],
  },
  {
    slug: 'seo',
    name: 'SEO',
    description: 'Search opportunities, landing-page improvements, and ranking deltas.',
    accent: '#76A8FF',
    status: 'blocked',
    focus: 'Preserve useful content improvements while reporting access is being restored.',
    queueCount: 2,
    botCount: 1,
    recentOutputCount: 4,
    routing: {
      intake: 'Site content changes and docs pages',
      review: 'Suggestions first',
      dispatch: 'Backlog and content edits',
    },
    assignedBots: ['Search Claw'],
    recentOutputs: [
      { id: 'seo-1', title: 'Docs index cleanup', kind: 'SEO suggestion', createdAtLabel: '21m ago', status: 'Needs review' },
      { id: 'seo-2', title: 'Search Console reconnect note', kind: 'System notice', createdAtLabel: '33m ago', status: 'Blocked' },
    ],
  },
  {
    slug: 'experiments',
    name: 'Experiments',
    description: 'Prompt trials, routing tests, and lightweight proof-of-concept work.',
    accent: '#B097FF',
    status: 'healthy',
    focus: 'Try small ideas quickly, then promote only the useful ones into stable lanes.',
    queueCount: 6,
    botCount: 2,
    recentOutputCount: 10,
    routing: {
      intake: 'Owner prompts and suggestion overflow',
      review: 'Suggestions and Outputs',
      dispatch: 'Whichever permanent pipeline earns the idea',
    },
    assignedBots: ['Experiment Log', 'Prompt Tuner'],
    recentOutputs: [
      { id: 'experiments-1', title: 'Prompt compression trial', kind: 'Workflow note', createdAtLabel: '5m ago', status: 'Ready' },
      { id: 'experiments-2', title: 'Alternate routing matrix', kind: 'Pipeline suggestion', createdAtLabel: '29m ago', status: 'Ready' },
    ],
  },
  {
    slug: 'custom-research',
    name: 'Custom Research',
    description: 'A quiet staging lane for imported bots, synthesis passes, and one-off investigations.',
    accent: '#8D95A4',
    status: 'watching',
    focus: 'Give imported bots a safe place to work before promoting them into primary pipelines.',
    queueCount: 3,
    botCount: 2,
    recentOutputCount: 5,
    routing: {
      intake: 'Imported configs and owner questions',
      review: 'Groupchat and Suggestions',
      dispatch: 'Product, marketing, or code depending on the synthesis',
    },
    assignedBots: ['Research Atlas', 'Import Stager'],
    recentOutputs: [
      { id: 'research-1', title: 'Imported bot capability matrix', kind: 'Import review', createdAtLabel: '31m ago', status: 'Needs review' },
      { id: 'research-2', title: 'Quiet UI references', kind: 'Research note', createdAtLabel: '1h ago', status: 'Queued' },
    ],
  },
];

export const ownerOutputs: OwnerOutput[] = [
  {
    id: 'output-1',
    title: 'Owner shell refinement brief',
    category: 'Code refinement',
    pipeline: 'code',
    pipelineLabel: 'Code',
    pipelineAccent: '#7C83FF',
    status: 'needs-review',
    author: 'Code Claw 03',
    destination: 'Code Refinements',
    createdAtLabel: '8m ago',
    excerpt: 'Replace the pipeline-first owner shell with a real multipage dashboard and move pipeline detail into a secondary route.',
    copyableText: 'Rebuild the owner dashboard as a true multipage operating system. Make Overview the default route, give Groupchat and Suggestions first-class pages, and keep the entire interface calm, light, and editorial.',
    routeTarget: 'Route to Code Refinements',
    href: '/dashboard/owner/code-refinements',
  },
  {
    id: 'output-2',
    title: 'Founder launch note rewrite',
    category: 'Copy draft',
    pipeline: 'marketing',
    pipelineLabel: 'Marketing',
    pipelineAccent: '#F29D85',
    status: 'ready',
    author: 'Launch Copy',
    destination: 'Outputs',
    createdAtLabel: '14m ago',
    excerpt: 'A calmer launch note written like a personal update from the founder rather than a campaign email.',
    copyableText: 'Rewrite the launch note in a founder voice. Keep it concise, grounded, and specific. Avoid hype language, marketing hooks, and startup clichés.',
    routeTarget: 'Send to Social',
    href: '/dashboard/owner/outputs',
  },
  {
    id: 'output-3',
    title: 'Founder thread starter',
    category: 'Social draft',
    pipeline: 'social',
    pipelineLabel: 'Social',
    pipelineAccent: '#7DC8C0',
    status: 'ready',
    author: 'Social Cut',
    destination: 'Outputs',
    createdAtLabel: '16m ago',
    excerpt: 'A short thread opener about building a calmer editing workspace and why Quartz exists.',
    copyableText: 'Turn the founder launch note into a short thread for X. Keep it observational and specific. Avoid shouting, emojis, and forced hooks.',
    routeTarget: 'Send to Cursor',
    href: '/dashboard/owner/outputs',
  },
  {
    id: 'output-4',
    title: 'Dashboard backlog cleanup',
    category: 'Product note',
    pipeline: 'product',
    pipelineLabel: 'Product',
    pipelineAccent: '#D7B47E',
    status: 'ready',
    author: 'Product Signal',
    destination: 'Suggestions',
    createdAtLabel: '12m ago',
    excerpt: 'A focused note describing which owner dashboard elements feel essential and which ones are ornamental.',
    copyableText: 'Review the owner dashboard backlog. Keep only pages and interactions that help the founder think, route work, and approve outputs. Remove filler analytics and generic admin components.',
    routeTarget: 'Route to Suggestions',
    href: '/dashboard/owner/suggestions',
  },
  {
    id: 'output-5',
    title: 'Docs index cleanup',
    category: 'SEO suggestion',
    pipeline: 'seo',
    pipelineLabel: 'SEO',
    pipelineAccent: '#76A8FF',
    status: 'queued',
    author: 'Search Claw',
    destination: 'Suggestions',
    createdAtLabel: '21m ago',
    excerpt: 'Internal linking opportunities for docs and guide pages so intent clusters stay tighter.',
    copyableText: 'Audit docs and guide pages. Suggest stronger internal linking between setup guidance, feature pages, and founder narrative content without using spammy SEO language.',
    routeTarget: 'Route to Product',
    href: '/dashboard/owner/suggestions',
  },
  {
    id: 'output-6',
    title: 'Imported bot capability matrix',
    category: 'Import review',
    pipeline: 'custom-research',
    pipelineLabel: 'Custom Research',
    pipelineAccent: '#8D95A4',
    status: 'needs-review',
    author: 'Import Stager',
    destination: 'Import Bot',
    createdAtLabel: '31m ago',
    excerpt: 'A structured comparison of staged bots so each one can land in the right pipeline with the right permissions.',
    copyableText: 'Inspect the imported bot bundle and list each bot, its best-fit pipeline, activation risk, and the minimum tool permissions it needs before going live.',
    routeTarget: 'Route to Bot Management',
    href: '/dashboard/owner/import-bot',
  },
];

export const ownerSuggestions: OwnerSuggestion[] = [
  {
    id: 'suggestion-1',
    title: 'Route owner UI work into Code before anything else',
    type: 'Pipeline',
    pipeline: 'code',
    pipelineLabel: 'Code',
    priority: 'High',
    createdAtLabel: '6m ago',
    summary: 'Owner shell and dashboard requests should default into Code so implementation work stays coherent.',
    whyNow: 'This prevents interface work from dissolving into a generic backlog or suggestion queue.',
    executionBrief: 'Update routing so any request involving dashboard UI, navigation, page structure, or interaction defaults into the Code pipeline first. Only fan out after a code-ready spec exists.',
    tags: ['routing', 'owner shell', 'code'],
  },
  {
    id: 'suggestion-2',
    title: 'Use threaded summaries at the end of major groupchat contexts',
    type: 'Workflow',
    pipeline: 'experiments',
    pipelineLabel: 'Experiments',
    priority: 'Medium',
    createdAtLabel: '11m ago',
    summary: 'Long chats need clean summaries that can move into suggestions, outputs, or refinement specs.',
    whyNow: 'Without a recap step, owner groupchat becomes memory work instead of an operating surface.',
    executionBrief: 'Add a summary command that asks the active claws to list decisions made, unresolved blockers, and the next best routing destination for each thread.',
    tags: ['groupchat', 'summaries', 'workflow'],
  },
  {
    id: 'suggestion-3',
    title: 'Keep code refinements in plain English only',
    type: 'Code refinement',
    pipeline: 'code',
    pipelineLabel: 'Code',
    priority: 'High',
    createdAtLabel: '15m ago',
    summary: 'The refinement page should never drift into raw diffs, console output, or implementation snippets.',
    whyNow: 'This page is a handoff surface for another AI or for you, so it needs stable copy-ready language.',
    executionBrief: 'Enforce a visible template for every refinement: Title, Files to Change, Suggestion, Why This Helps, Alternative Approaches.',
    tags: ['code refinements', 'copy-ready', 'owner workflow'],
  },
  {
    id: 'suggestion-4',
    title: 'Turn imported bot previews into a capability scorecard',
    type: 'Product',
    pipeline: 'custom-research',
    pipelineLabel: 'Custom Research',
    priority: 'Medium',
    createdAtLabel: '18m ago',
    summary: 'Imported configs are easier to trust when each bot is scored by relevance, permission risk, and routing fit.',
    whyNow: 'The import step should feel deliberate instead of like a raw JSON dump.',
    executionBrief: 'Show each staged bot with a role summary, safest default pipeline, and a visible permission risk check before activation.',
    tags: ['imports', 'bot review', 'product'],
  },
  {
    id: 'suggestion-5',
    title: 'Tie launch messaging to actual owner workflow moments',
    type: 'Marketing',
    pipeline: 'marketing',
    pipelineLabel: 'Marketing',
    priority: 'Low',
    createdAtLabel: '23m ago',
    summary: 'Quartz copy is strongest when it describes real behavior instead of category language.',
    whyNow: 'The new dashboard structure exposes concrete behaviors worth describing in launch materials.',
    executionBrief: 'When drafting launch copy, anchor each claim in a real owner workflow like reviewing outputs, switching to groupchat, approving refinements, or importing a bot.',
    tags: ['founder voice', 'copy', 'positioning'],
  },
];

export const importedBotPackages: ImportedBotPackage[] = [
  {
    id: 'import-1',
    source: 'OpenClaw',
    fileName: 'launch-week.openclaw.json',
    importedAtLabel: '12m ago',
    status: 'staged',
    notes: 'Three imported bots are waiting for pipeline assignment and permission review.',
    preview: '{\n  name: launch-week,\n  defaultModel: gpt-4.1,\n  bots: [Hook Draft, Founder Voice, Reply Triage]\n}',
    assignments: [
      { id: 'assignment-1', name: 'Hook Draft', role: 'social variations', pipeline: 'social', pipelineLabel: 'Social', active: false },
      { id: 'assignment-2', name: 'Founder Voice', role: 'launch copy cleanup', pipeline: 'marketing', pipelineLabel: 'Marketing', active: false },
      { id: 'assignment-3', name: 'Reply Triage', role: 'community routing', pipeline: 'custom-research', pipelineLabel: 'Custom Research', active: false },
    ],
  },
  {
    id: 'import-2',
    source: 'KiloClaw',
    fileName: 'owner-specs.kiloclaw.json',
    importedAtLabel: '1h ago',
    status: 'active',
    notes: 'A small specs helper bundle is already live inside the Code pipeline.',
    preview: '{\n  bundle: owner-specs,\n  pipeline: code,\n  bots: [Spec Weaver, Review Claw]\n}',
    assignments: [
      { id: 'assignment-4', name: 'Spec Weaver', role: 'execution formatter', pipeline: 'code', pipelineLabel: 'Code', active: true },
      { id: 'assignment-5', name: 'Review Claw', role: 'quality pass', pipeline: 'code', pipelineLabel: 'Code', active: true },
    ],
  },
  {
    id: 'import-3',
    source: 'OpenClaw',
    fileName: 'research-scout.openclaw.json',
    importedAtLabel: 'Yesterday',
    status: 'needs-review',
    notes: 'One imported bot is asking for broader permissions than it should have.',
    preview: '{\n  name: research-scout,\n  requestedTools: [web, notes, command],\n  bots: [Research Atlas]\n}',
    assignments: [
      { id: 'assignment-6', name: 'Research Atlas', role: 'imported research synthesis', pipeline: 'custom-research', pipelineLabel: 'Custom Research', active: false },
    ],
  },
];

export const ownerBots: BotRecord[] = [
  {
    id: 'bot-1',
    name: 'Quartz Prime',
    role: 'Owner coordinator',
    pipeline: 'overview',
    pipelineLabel: 'Overview',
    model: 'gpt-5.4',
    status: 'active',
    permissions: ['route work', 'summarize threads', 'open approvals'],
    tools: ['groupchat', 'outputs', 'suggestions'],
    lastAction: 'Prepared the morning owner briefing',
    recentActions: ['Clustered overnight work into approvals and alerts', 'Opened the dashboard rebuild context', 'Routed UI work into the Code pipeline'],
    logs: ['02:52 — Briefing prepared from 14 events', '02:47 — Owner HQ context set active', '02:39 — Approval queue refreshed'],
  },
  {
    id: 'bot-2',
    name: 'Code Claw 03',
    role: 'Interface refinement',
    pipeline: 'code',
    pipelineLabel: 'Code',
    model: 'claude-3.7-sonnet',
    status: 'active',
    permissions: ['draft refinement specs', 'inspect UI architecture'],
    tools: ['code refinements', 'outputs', 'groupchat'],
    lastAction: 'Drafted the owner shell refinement brief',
    recentActions: ['Compared current owner layout against requested route map', 'Prepared a route-by-route implementation plan', 'Flagged the old pipeline route as legacy'],
    logs: ['02:46 — Refinement brief queued', '02:28 — Layout diff completed', '02:14 — Sidebar scope updated'],
  },
  {
    id: 'bot-3',
    name: 'Spec Weaver',
    role: 'Execution formatter',
    pipeline: 'code',
    pipelineLabel: 'Code',
    model: 'gpt-4.1',
    status: 'watching',
    permissions: ['rewrite specs', 'structure handoff text'],
    tools: ['code refinements', 'suggestions'],
    lastAction: 'Normalized the code refinement template',
    recentActions: ['Expanded alternative approach sections', 'Reformatted file lists', 'Held back raw diff output'],
    logs: ['02:31 — Waiting for approval', '02:11 — Refinement schema updated', '01:56 — Handoff wording cleaned'],
  },
  {
    id: 'bot-4',
    name: 'Launch Copy',
    role: 'Founder note drafting',
    pipeline: 'marketing',
    pipelineLabel: 'Marketing',
    model: 'gpt-4o',
    status: 'active',
    permissions: ['draft copy', 'route to social'],
    tools: ['outputs', 'suggestions'],
    lastAction: 'Rewrote the founder launch note',
    recentActions: ['Produced a shorter intro', 'Matched the founder tone', 'Queued a social derivative request'],
    logs: ['02:40 — Launch note ready', '02:19 — Tone pass completed', '01:58 — Social derivative request filed'],
  },
  {
    id: 'bot-5',
    name: 'Search Claw',
    role: 'Search insight monitor',
    pipeline: 'seo',
    pipelineLabel: 'SEO',
    model: 'sonnet-reasoning',
    status: 'offline',
    permissions: ['read SEO notes', 'suggest content changes'],
    tools: ['suggestions', 'outputs'],
    lastAction: 'Flagged stale Search Console credentials',
    recentActions: ['Paused live delta comparison', 'Queued cached content notes', 'Requested credential refresh'],
    logs: ['02:33 — Credentials missing', '02:07 — Cached mode enabled', '01:44 — Fallback switched to suggestions'],
  },
  {
    id: 'bot-6',
    name: 'Research Atlas',
    role: 'Imported research synthesis',
    pipeline: 'custom-research',
    pipelineLabel: 'Custom Research',
    model: 'gpt-4o-mini',
    status: 'paused',
    permissions: ['read staged configs', 'summarize capability fit'],
    tools: ['import bot', 'suggestions'],
    lastAction: 'Prepared a capability matrix for the import bundle',
    recentActions: ['Compared imported bot roles against pipelines', 'Prepared a quiet UI reference sweep', 'Paused until routing is approved'],
    logs: ['02:23 — Capability matrix ready', '02:03 — Bundle parsed', '01:48 — Research lane paused'],
  },
];

export const codeRefinementSpecs: CodeRefinementSpec[] = [
  {
    id: 'refinement-1',
    title: 'Replace the old pipeline-first owner shell with a real multipage layout',
    pipelineLabel: 'Code',
    filesToChange: ['app/dashboard/owner/layout.tsx', 'app/dashboard/owner/page.tsx', 'components/owner/OwnerSidebar.tsx'],
    suggestion: 'Create a shared owner shell with a sidebar for Overview, Pipelines, Groupchat, Suggestions, Import Bot, Bot Management, Outputs, Code Refinements, and Settings. Make Overview the default landing page.',
    whyThisHelps: 'The dashboard finally reflects the real product structure instead of forcing every owner task through pipelines.',
    alternativeApproaches: ['Keep a secondary pipeline nav inside the Pipelines page only.', 'Use a compact top nav on smaller screens while preserving the full desktop sidebar.'],
  },
  {
    id: 'refinement-2',
    title: 'Make groupchat a first-class workspace instead of a floating footer',
    pipelineLabel: 'Code',
    filesToChange: ['app/dashboard/owner/groupchat/page.tsx', 'components/owner/KiloClawChat.tsx'],
    suggestion: 'Move groupchat into its own page with context switching, thread labels, active task visibility, and a command composer that can target the current conversation.',
    whyThisHelps: 'Groupchat becomes a real operating surface rather than a secondary widget attached to a feed.',
    alternativeApproaches: ['Keep a tiny global launcher that deep-links into the full groupchat page.', 'Allow the context summary panel to collapse on smaller screens.'],
  },
  {
    id: 'refinement-3',
    title: 'Turn code outputs into plain-English execution specs',
    pipelineLabel: 'Code',
    filesToChange: ['app/dashboard/owner/code-refinements/page.tsx', 'lib/owner/data.ts'],
    suggestion: 'Render each refinement with stable sections for Title, Files to Change, Suggestion, Why This Helps, and Alternative Approaches. Keep the copy action faithful to that structure.',
    whyThisHelps: 'Each refinement becomes clean handoff material for another AI or a manual implementation pass.',
    alternativeApproaches: ['Keep hidden implementation notes for internal debugging only.', 'Group refinements by pipeline if the list grows later.'],
  },
  {
    id: 'refinement-4',
    title: 'Use a typed mock-data layer that mirrors future API contracts',
    pipelineLabel: 'Code',
    filesToChange: ['lib/owner/types.ts', 'lib/owner/data.ts', 'app/dashboard/owner/pipelines/[pipeline]/page.tsx'],
    suggestion: 'Drive the UI with typed mock data for overview signals, pipelines, outputs, suggestions, imports, bots, groupchat contexts, refinements, and settings.',
    whyThisHelps: 'The dashboard can ship now and later swap data sources without a structural rewrite.',
    alternativeApproaches: ['Split data by domain if the file grows later.', 'Add server loaders that return the same types when Prisma is connected.'],
  },
];

export const groupchatContexts: GroupchatContext[] = [
  {
    id: 'owner-hq',
    label: 'Owner HQ',
    description: 'The main room for routing work, clearing blockers, and asking the claws for clean status passes.',
    unreadCount: 2,
    participants: [
      { id: 'participant-1', name: 'Quartz Prime', role: 'Coordinator', pipelineLabel: 'Overview', status: 'Listening' },
      { id: 'participant-2', name: 'Code Claw 03', role: 'Interface refinement', pipelineLabel: 'Code', status: 'Drafting spec' },
      { id: 'participant-3', name: 'Launch Copy', role: 'Founder language', pipelineLabel: 'Marketing', status: 'Waiting for approval' },
    ],
    pinnedCommands: ['Summarize anything blocked right now.', 'Route the top three outputs into the right pages.', 'Prepare a clean owner briefing for the next hour.'],
    threads: [
      { id: 'thread-1', label: 'Dashboard rebuild', summary: 'Route map, reusable components, and mock data.', openItems: 3 },
      { id: 'thread-2', label: 'Launch note', summary: 'Founder language pass before distribution.', openItems: 1 },
      { id: 'thread-3', label: 'SEO credentials', summary: 'Reconnect Search Console and resume deltas.', openItems: 1 },
    ],
    tasks: [
      { id: 'task-1', title: 'Map owner routes to the new shell', owner: 'Code Claw 03', status: 'Running', eta: '8m' },
      { id: 'task-2', title: 'Shorten founder launch note intro', owner: 'Launch Copy', status: 'Review', eta: 'Ready' },
      { id: 'task-3', title: 'Confirm import bundle assignments', owner: 'Research Atlas', status: 'Queued', eta: 'After approval' },
    ],
    messages: [
      { id: 'message-1', agentName: 'Quartz Prime', role: 'Coordinator', content: 'Morning pass is ready. Code routing still needs correction, SEO credentials are stale, and the launch-week import bundle is staged but inactive.', createdAtLabel: '16m ago', isOwner: false },
      { id: 'message-2', agentName: 'Owner', role: 'Owner', content: 'Keep the owner dashboard clean and multipage. Pipelines are only one lane. Groupchat and suggestions should both feel first-class.', createdAtLabel: '14m ago', isOwner: true, replyToLabel: 'Dashboard rebuild' },
      { id: 'message-3', agentName: 'Code Claw 03', role: 'Interface refinement', content: 'Understood. I am reframing the shell around nine real pages and moving pipeline detail into a secondary route under Pipelines.', createdAtLabel: '10m ago', isOwner: false, replyToLabel: 'Dashboard rebuild' },
    ],
  },
  {
    id: 'code-room',
    label: 'Code War Room',
    description: 'Focused context for interface changes, refinement specs, and implementation sequencing.',
    unreadCount: 0,
    participants: [
      { id: 'participant-4', name: 'Code Claw 03', role: 'Interface refinement', pipelineLabel: 'Code', status: 'Implementing' },
      { id: 'participant-5', name: 'Spec Weaver', role: 'Execution formatter', pipelineLabel: 'Code', status: 'Normalizing handoff' },
      { id: 'participant-6', name: 'Review Claw', role: 'Quality pass', pipelineLabel: 'Code', status: 'Checking edge cases' },
    ],
    pinnedCommands: ['Turn this into a copy-ready refinement spec.', 'List only the files that actually need to change.', 'Explain the safest implementation order.'],
    threads: [
      { id: 'thread-4', label: 'Shell layout', summary: 'Sidebar, content frame, and responsive spacing.', openItems: 2 },
      { id: 'thread-5', label: 'Groupchat workspace', summary: 'Context switcher, message stack, command composer.', openItems: 1 },
    ],
    tasks: [
      { id: 'task-4', title: 'Refit reusable page primitives', owner: 'Spec Weaver', status: 'Running', eta: '4m' },
      { id: 'task-5', title: 'Verify pipeline detail route', owner: 'Review Claw', status: 'Review', eta: 'Ready' },
    ],
    messages: [
      { id: 'message-4', agentName: 'Spec Weaver', role: 'Execution formatter', content: 'The code refinement structure is stable and can be copied directly into another AI without cleanup.', createdAtLabel: '25m ago', isOwner: false },
      { id: 'message-5', agentName: 'Review Claw', role: 'Quality pass', content: 'The route tree should live under /dashboard/owner with pipeline detail nested at /pipelines/[pipeline] so pipelines stay secondary.', createdAtLabel: '19m ago', isOwner: false, replyToLabel: 'Shell layout' },
      { id: 'message-6', agentName: 'Owner', role: 'Owner', content: 'Keep everything light, editorial, and quiet. No dark command-center energy and no generic admin template moves.', createdAtLabel: '17m ago', isOwner: true, replyToLabel: 'Shell layout' },
    ],
  },
];

export const ownerSettingSections: OwnerSettingSection[] = [
  {
    id: 'settings-1',
    title: 'Owner access',
    description: 'Authentication, verification, and session defaults for the private owner area.',
    fields: [
      { id: 'auth-1', label: 'Require owner verification', description: 'Keep hardware or session verification enabled before loading the owner shell.', type: 'toggle', value: true },
      { id: 'auth-2', label: 'Fallback owner email', description: 'Primary email allowed to enter the owner dashboard.', type: 'text', value: 'aiden@quartzeditor.com' },
    ],
  },
  {
    id: 'settings-2',
    title: 'Bot defaults',
    description: 'Default behavior for newly created or imported claws.',
    fields: [
      { id: 'bot-1', label: 'Default model', description: 'Preferred model when a bundle does not specify one.', type: 'select', value: 'gpt-5.4', options: ['gpt-5.4', 'claude-3.7-sonnet', 'gpt-4.1'] },
      { id: 'bot-2', label: 'Allow imported bots to start active', description: 'If disabled, every imported bot stays staged until reviewed.', type: 'toggle', value: false },
    ],
  },
  {
    id: 'settings-3',
    title: 'Pipeline routing rules',
    description: 'Default routing behavior between groupchat, suggestions, outputs, and code refinements.',
    fields: [
      { id: 'routing-1', label: 'Owner UI work default lane', description: 'Where dashboard, navigation, and owner shell requests should go first.', type: 'select', value: 'Code', options: ['Code', 'Product', 'Suggestions'] },
      { id: 'routing-2', label: 'Groupchat summary cadence', description: 'How often active contexts should request a clean summary.', type: 'select', value: 'Every major thread', options: ['Manual only', 'Every major thread', 'Every 30 minutes'] },
    ],
  },
  {
    id: 'settings-4',
    title: 'API keys and integrations',
    description: 'Credentials for KiloClaw, OpenClaw, and other owner-facing integrations.',
    fields: [
      { id: 'api-1', label: 'KiloClaw API key', description: 'Used for live command routing and bot management.', type: 'password', value: '••••••••••••••••' },
      { id: 'api-2', label: 'Search Console connection note', description: 'Current SEO integration status and next action.', type: 'textarea', value: 'Reconnect Search Console to restore daily ranking deltas.' },
    ],
  },
  {
    id: 'settings-5',
    title: 'UI preferences',
    description: 'Quiet interface defaults for the owner operating system.',
    fields: [
      { id: 'ui-1', label: 'Keep light theme locked', description: 'Preserve the light Quartz dashboard presentation.', type: 'toggle', value: true },
      { id: 'ui-2', label: 'Dense list mode', description: 'Reduce spacing slightly in long outputs or bot tables.', type: 'toggle', value: false },
    ],
  },
];

export function getPipelineBySlug(slug: string) {
  return ownerPipelines.find((pipeline) => pipeline.slug === slug);
}

export function getOutputsForPipeline(slug: string) {
  return ownerOutputs.filter((output) => output.pipeline === slug);
}

export function getSuggestionsForPipeline(slug: string) {
  return ownerSuggestions.filter((suggestion) => suggestion.pipeline === slug);
}

export function getGroupchatContext(id: string) {
  return groupchatContexts.find((context) => context.id === id) ?? groupchatContexts[0];
}
